trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  azureServiceConnection: 'Resource Manager - Tailspin - Space Game'

steps:
- task: AzureCLI@2
  displayName: 'Run Azure CLI'
  inputs:
    azureSubscription: $(azureServiceConnection)   # ðŸ‘ˆ service connection name
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      az account show
      az group list
